- name: enable epel
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
- name: Check for custom python
  stat:
    path: /usr/local/bin/python2.7
  register: python_result
- name: Extract Python 2.7.15
  unarchive:
    src: https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tgz
    dest: /tmp/
    remote_src: yes
    validate_certs: yes
  when: python_result.stat.exists == False
- name: Configure Python 2.7.15
  shell: ./configure --prefix=/usr/local
  args:
    chdir: /tmp/Python-2.7.15
  when: python_result.stat.exists == False
- name: Install Python 2.7.15
  shell: make && make altinstall
  args:
    chdir: /tmp/Python-2.7.15
  when: python_result.stat.exists == False
- name: Check for custom python
  stat:
    path: /usr/local/bin/pip
  register: pip_result
- name: Download pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    validate_certs: yes
  when: pip_result.stat.exists == False
- name: Install pip
  shell: /usr/local/bin/python2.7 /tmp/get-pip.py
  when: pip_result.stat.exists == False
